# Generated by Django 2.2 on 2019-04-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdsys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='tcolor',
        ),
    ]
