# Generated by Django 2.2 on 2019-04-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdsys', '0004_auto_20190427_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tcolor',
            field=models.CharField(default='prime', max_length=20),
        ),
    ]
