# Generated by Django 2.2 on 2019-04-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdsys', '0005_tag_tcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sgrade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='smajor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
