# Generated by Django 2.2 on 2019-04-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdsys', '0006_auto_20190428_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='smajor',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
