# Generated by Django 2.2 on 2019-04-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdsys', '0007_auto_20190428_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sclass',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='smajor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='ssex',
            field=models.CharField(max_length=1),
        ),
    ]
