# Generated by Django 2.2 on 2019-04-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdsys', '0008_auto_20190428_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tdisplay',
            field=models.BooleanField(default=True),
        ),
    ]
