# Generated by Django 2.2 on 2019-04-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdsys', '0009_tag_tdisplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=10)),
            ],
        ),
    ]
