# Generated by Django 2.2 on 2019-04-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdsys', '0010_grade_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tcolor',
            field=models.CharField(default='waring', max_length=20),
        ),
    ]
