# Generated by Django 2.2 on 2019-04-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdsys', '0011_auto_20190430_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='sbanji',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
