# Generated by Django 2.2 on 2019-04-30 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdsys', '0012_auto_20190430_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sbanji',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sgrade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='smajor',
        ),
    ]
