# Generated by Django 2.2 on 2019-04-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdsys', '0013_auto_20190430_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sbanji',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sgrade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='smajor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
